# Example Ray Tune configuration YAML for a GeoCLIP + YFCC100M generation run

ray:
  # Configuration for Ray cluster (local or remote)
  address: null         # Use 'auto' for Ray on cluster, or null for local

parameters:
  model_name: geoclip
  dataset_name: yfcc100m
  transform_name: geoclip
  batch_size: 128
  num_workers: 6
  max_shards: 20  
