

model: 
  arch_name: "dinov2"
  dataset_name: "yfcc100m"
  pred_model_name: "geoclip"
  learning_rate: 0.0001
  weight_decay: 0.00001
  scheduler: 'cosine'
  warmup_steps: 10
  min_lr: 0.00001
  loss_alpha: 1.0
  loss_beta: 0.1
  batch_size: 32
  num_workers: 8

  
trainer: 
  max_steps: 100000
  val_check_interval: 18000
  limit_val_batches: 100
  precision: 'bf16-mixed' 
  accelerator: 'auto'
  devices: 'auto'
  strategy: 'auto'
  log_every_n_steps: 10
  enable_progress_bar: False
  check_val_every_n_epoch: 0 


checkpoint: True 
logger: True 