

model: 
  arch_name: "megaloc"
  dataset_name: "yfcc100m"
  pred_model_name: "geoclip"
  learning_rate: 0.0001
  weight_decay: 0.0
  scheduler: 'cosine'
  warmup_steps: 10
  min_lr: 0.00001
  loss_alpha: 1.0
  loss_beta: 0.1
  batch_size: 32
  num_workers: 8

  
trainer: 
  max_steps: 100000
  val_check_interval: 100000
  limit_val_batches: 100
  precision: 'bf16-mixed'  # Changed from 16 to 32 for stability with MegaLoc
  accelerator: 'auto'
  devices: 'auto'
  strategy: 'auto'
  log_every_n_steps: 10
  enabel_progress_bar: False


checkpoint: True 
logger: True 